---
# Series y DataFrames

- Lectura de datos
- Métodos básicos de exploración
- La estructura Serie
- La estructura DataFrame
- Selección de subset de datos
- Operacione estadísticas
- Filtrado de datos
- Creación de columnas en un dataframe

In [1]:
import pandas as pd

#### Leemos los datos desde un archivo

In [2]:
df = pd.read_csv('https://patricioaraneda.cl/public/titanic3.csv')

#### Métodos básicos de exploración de un DataFrame

In [3]:
df.head(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"

In [4]:
df.tail(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.225,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.875,NaN,S,NaN,NaN,NaN

In [5]:
df.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB

#### La Serie

Seleccionando una columna del DataFrame

In [8]:
df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

Seleccionando una Fila del DataFrame

In [9]:
df.iloc[0]

pclass                                   1
survived                                 1
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                   29.0
sibsp                                    0
parch                                    0
ticket                               24160
fare                              211.3375
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

#### Seleccionando columnas de un DataFrame

In [10]:
df[ ['name','age'] ]

                                                 name      age
0                       Allen, Miss. Elisabeth Walton  29.0000
1                      Allison, Master. Hudson Trevor   0.9167
2                        Allison, Miss. Helen Loraine   2.0000
3                Allison, Mr. Hudson Joshua Creighton  30.0000
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000
...                                               ...      ...
1304                             Zabour, Miss. Hileni  14.5000
1305                            Zabour, Miss. Thamine      NaN
1306                        Zakarian, Mr. Mapriededer  26.5000
1307                              Zakarian, Mr. Ortin  27.0000
1308                               Zimmerman, Mr. Leo  29.0000

[1309 rows x 2 columns]

In [11]:
df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

#### Seleccionando filas de un DataFrame

In [12]:
df.iloc[5]

pclass                         1
survived                       1
name         Anderson, Mr. Harry
sex                         male
age                         48.0
sibsp                          0
parch                          0
ticket                     19952
fare                       26.55
cabin                        E12
embarked                       S
boat                           3
body                         NaN
home.dest           New York, NY
Name: 5, dtype: object

In [13]:
df.iloc[5:8]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
5,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"

In [14]:
df.iloc[ [5,7,9] ]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
5,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

#### Seleccionando celdas

In [15]:
df.loc[2:5, 'name']

2                       Allison, Miss. Helen Loraine
3               Allison, Mr. Hudson Joshua Creighton
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
5                                Anderson, Mr. Harry
Name: name, dtype: object

In [16]:
df.loc[2:5, ['name','age']]

                                              name   age
2                     Allison, Miss. Helen Loraine   2.0
3             Allison, Mr. Hudson Joshua Creighton  30.0
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0
5                              Anderson, Mr. Harry  48.0

#### Realizando Cálculos Estadísticos en una Serie o DataFrame

In [33]:
df.min(numeric_only=True)

pclass      1.0000
survived    0.0000
age         0.1667
sibsp       0.0000
parch       0.0000
fare        0.0000
body        1.0000
dtype: float64

In [19]:
df['fare'].min()

0.0

In [32]:
df.max(numeric_only=True)

pclass        3.0000
survived      1.0000
age          80.0000
sibsp         8.0000
parch         9.0000
fare        512.3292
body        328.0000
dtype: float64

In [31]:
df['fare'].max()

512.3292

In [21]:
df.count()

pclass       1309
survived     1309
name         1309
sex          1309
age          1046
sibsp        1309
parch        1309
ticket       1309
fare         1308
cabin         295
embarked     1307
boat          486
body          121
home.dest     745
dtype: int64

In [23]:
df['fare'].count()

np.int64(1308)

In [34]:
df.median(numeric_only=True)

pclass        3.0000
survived      0.0000
age          28.0000
sibsp         0.0000
parch         0.0000
fare         14.4542
body        155.0000
dtype: float64

In [26]:
df['fare'].median()

14.4542

In [ ]:
df.mean()

PassengerId    50.500000
Survived        0.410000
Pclass          2.400000
Age            27.465769
SibSp           0.730000
Parch           0.440000
Fare           29.517625
dtype: float64

In [27]:
df['fare'].mean()

np.float64(33.29547928134557)

In [35]:
df.quantile(q=0.1, numeric_only=True)

pclass       1.0000
survived     0.0000
age         14.0000
sibsp        0.0000
parch        0.0000
fare         7.5675
body        35.0000
Name: 0.1, dtype: float64

In [29]:
df['fare'].quantile(q=0.1)

np.float64(7.567500000000001)

In [ ]:
df.quantile(q=0.5)

PassengerId    50.500
Survived        0.000
Pclass          3.000
Age            26.000
SibSp           0.000
Parch           0.000
Fare           15.675
Name: 0.5, dtype: float64

In [36]:
df['fare'].quantile(q=0.5)

np.float64(14.4542)

In [38]:
df.quantile(q=0.9, numeric_only=True)

pclass        3.00000
survived      1.00000
age          50.00000
sibsp         1.00000
parch         2.00000
fare         78.05082
body        297.00000
Name: 0.9, dtype: float64

In [39]:
df['fare'].quantile(q=0.9)

np.float64(78.05081999999999)

#### Filtrando Filas de un DataFrame

In [41]:
df[ df['fare'] > 500  ]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Austria-Hungary / Germantown, Philadelphia, PA"
50,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Germantown, Philadelphia, PA"
183,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,3,NaN,NaN
302,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,3,NaN,NaN

In [42]:
df[ (df['fare'] > 500) & (df['sex'] == 'female') ]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
50,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Germantown, Philadelphia, PA"
302,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,3,NaN,NaN

#### Agregar columnas al dataframe

In [43]:
df['taxes'] = 5

In [ ]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Taxes
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,5
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,5

In [44]:
df['taxes'] = df['fare'] * 0.05 + 1

In [45]:
df.head(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,taxes
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",11.566875
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",8.577500

In [46]:
df['total'] = df['fare'] + df['taxes']

In [47]:
df.head(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,taxes,total
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",11.566875,222.904375
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",8.577500,160.127500

### Creación de Estructuras desde Cero

In [48]:
mi_serie = pd.Series(data=[17.9, 43.8, 207.7, 31.77], index=['CL','AR','BR','PE'])

In [ ]:
mi_serie

CL     17.90
AR     43.80
BR    207.70
PE     31.77
dtype: float64

In [50]:
type(mi_serie)

pandas.core.series.Series

In [51]:
datos = [['Juan',25],['Pedro',28],['Miguel',30]]
columnas = ['Nombre','Edad']

In [52]:
mi_dataframe = pd.DataFrame(data=datos, columns=columnas)

In [ ]:
mi_dataframe

   Nombre  Edad
0    Juan    25
1   Pedro    28
2  Miguel    30

In [53]:
type(mi_dataframe)

pandas.core.frame.DataFrame

### Eliminar filas y columnas

In [55]:
df.drop('total', axis=1, inplace=True)

KeyError: "['total'] not found in axis"

In [56]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,taxes
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",11.566875
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",8.577500
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",8.577500
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",8.577500
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",8.577500

In [57]:
df.drop(0, axis=0, inplace=True)

In [58]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,taxes
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",8.5775
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.55,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",8.5775
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.55,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",8.5775
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.55,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",8.5775
5,1,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.55,E12,S,3,NaN,"New York, NY",2.3275